#! /bin/sh

case "$@" in

all)
	clear
	;;

you)
	exit
	;;

yes)
	yes "fuck"
	;;

"the system"|"off")
	sudo halt -p
	;;

yeah)
echo ""
echo "                 _. _,,            "
echo "               _a%?9wau\"5a,.       "
echo "            .a\"?4owdZ'']&%6.       "
echo "           <!   ._aaaa,;?)T5.      "
echo "          <'   \"-    -<w[c -r        ______________"
echo "          o              +c [       /              \\"
echo "          4                :(      <   FUCK YEAH!   |"
echo "           5               ]\`       \\______________/"
echo "            ?/            _[       "
echo "             -!aa;4,    _%'.       "
echo "          _a,?\"  ?4B????-          "
echo "        v(         FL              "
echo "       j'          C-L             "
echo "      <(           j -\\/           "
echo "     j'            )c  -?a,        "
echo "    jLa.            \\     ~?\\a,    "
echo "   Jf1 !.           \"c        :Wc  "
echo "   c):\"              3        ))\$ "
echo ""
;;

"with me")
while true; do
clear
echo
echo " \\O/"
echo "  |"
echo " / \\"
echo
sleep 0.5
clear
echo
echo "  O"
echo " (|)"
echo " / \\"
echo
sleep 0.5
done
;;

*)
	if [ -n "$1" ]
	then
		if [ `echo "$1" | grep -c "^[0-9]*$"` -eq 1 ]
		then
			kill "$1"
		else
			pkill "$1"
		fi
		
	else
		echo "what the fuck?"
		printf "\tfuck you - exit terminal.\n"
		printf "\tfuck the system - shutdown the system.\n"
		printf "\tfuck yes - stubbornly rages against the user.\n"
		printf "\tfuck off - shutdown the system.\n"
		printf "\tfuck all - clear the screen.\n"
		printf "\tfuck yeah - useless but very cool ;)\n"
		printf "\tfuck <PROC> - pkill <PROC> (e.g. fuck firefox)\n"
		printf "\tfuck <PID> - kill <PID>\n"
		printf "\tfuck with me - just fucks with you.\n"
	fi
esac

